apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kafka
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/bitnami/charts/tree/main/bitnami/kafka
    chart: kafka  # Specify the Helm chart name
    targetRevision: latest
    helm:
      valueFiles:
        - kafka-values.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kafka
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
