apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-exporter
  template:
    metadata:
      labels:
        app: kafka-exporter
    spec:
      containers:
      - name: kafka-exporter
        image: danielqsj/kafka-exporter:latest
        ports:
        - containerPort: 9308
        env:
        - name: KAFKA_BROKERS
          value: "PLAINTEXT://<your-kafka-broker>:9092" # Replace with your Kafka broker URL
        - name: KAFKA_VERSION
          value: "2.7.0" # Set this to your Kafka version
---
apiVersion: v1
kind: Service
metadata:
  name: kafka-exporter
  namespace: kafka
  labels:
    app: kafka-exporter
spec:
  ports:
  - name: http
    port: 9308
    targetPort: 9308
  selector:
    app: kafka-exporter
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: kafka-exporter
  namespace: default
  labels:
    release: prometheus-operator
spec:
  selector:
    matchLabels:
      app: kafka-exporter
  endpoints:
    - port: http
  namespaceSelector:
    matchNames:
      - kafka
