apiVersion: apps/v1
kind: Deployment
metadata:
  name: clickhouse-deployment
  namespace: clickhouse
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      containers:
        - name: clickhouse-server
          image: clickhouse/clickhouse-server:latest
          ports:
            - containerPort: 8123
            - containerPort: 9000
          volumeMounts:
            - name: clickhouse-storage
              mountPath: /var/lib/clickhouse
      volumes:
        - name: clickhouse-storage
          persistentVolumeClaim:
            claimName: clickhouse-pvc
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: clickhouse
  name: clickhouse-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # Adjust this as per your storage needs
---
apiVersion: v1
kind: Service
metadata:
  namespace: clickhouse
  name: clickhouse-service
spec:
  selector:
    app: clickhouse
  ports:
    - protocol: TCP
      name: http
      port: 8123  # HTTP interface
      targetPort: 8123
    - protocol: TCP
      name: tcp
      port: 9000  # Native TCP interface
      targetPort: 9000
  type: ClusterIP  # Use LoadBalancer if you want external access
