apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  generation: 1
  labels:
    app: redpanda
    app.kubernetes.io/instance: redpanda
    app.kubernetes.io/version: 62.7.0
    release: prometheus-operator
  name: prometheus-redpanda
  namespace: default
spec:
  endpoints:
  - path: /metrics
    port: admin
    interval: 30s
    enableHttp2: true
  - path: /public_metrics
    port: admin
    interval: 30s
    enableHttp2: true
  namespaceSelector:
    matchNames:
    - redpanda
  selector:
    matchLabels:
      app.kubernetes.io/name: redpanda
      app.kubernetes.io/instance: redpanda
