{
 "title": "Kafka Overview",
 "description": "Kafka resource usage and throughput",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Brokers Online",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "kafka_brokers" }
   ]
  },
  {
   "title": "Active Controllers",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(kafka_controller_kafkacontroller_activecontrollercount_value)"
    }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_underminisrpartitioncount_value)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions Count",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_atminisrpartitioncount_value)"
    }
   ]
  },
  {
   "title": "Partition Leader Distribution STDDEV",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stddev(kafka_topic_partition_leader)"
    }
   ]
  },
  {
   "title": "Partition Distribution STDDEV",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 21, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "stddev(kafka_server_replicamanager_total_partitioncount_value)"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{service=\"kafka-exporter\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "JVM Memory Used",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(area)(container_memory_usage_bytes{pod=\"kafka-controller-0\",container=\"kafka\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum without(area)(container_memory_usage_bytes{pod=\"kafka-controller-1\",container=\"kafka\"})",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "sum without(area)(container_memory_usage_bytes{pod=\"kafka-controller-2\",container=\"kafka\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Brokers Online",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_brokers", "legendFormat": "{{namespace}}" }
   ]
  },
  {
   "title": "Under Replicated Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_topic_partition_under_replicated_partition",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Under Min ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_underminisrpartitioncount_value",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "At Min ISR Partitions",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kafka_server_replicamanager_total_atminisrpartitioncount_value",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Partitions Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "expr": "kafka_topic_partitions", "legendFormat": "{{instance}}" }
   ]
  },
  {
   "title": "Partitions Leader Count",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(kafka_server_replicamanager_total_leadercount_value)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Messages In Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_total_messagesinpersec_count[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes In Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_total_bytesinpersec_count[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  },
  {
   "title": "Bytes Out Per Pod",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 27 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum without(instance)(increase(kafka_server_brokertopicmetrics_total_bytesoutpersec_count[$__interval]))",
     "legendFormat": "{{pod}}"
    }
   ]
  }
 ]
}